#KubeJS Common Properties
#Fri Feb 16 22:33:02 CET 2024
announceReload=true
disableClassFilter=false
serverOnly=false
hideServerScriptErrors=false
packmode=default
printRemappedClasses=false
debugInfo=false
